# Site settings
title: Chaim Leib Halbert
author: Chaim Leib Halbert
email: chaim.leib.halbert@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  <ul>Other blogs:
      <li><a href='https://manhacking.blogspot.com/'>man hacking</a></li>
      <li><a href='https://unlabeledjew.blogspot.com/'>Unlabeled Jew</a></li>
  </ul>
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://chaimleib.github.io" # the base hostname & protocol for your site
lang: en
twitter_username: ChaimHalbert
github_username: chaimleib

# Build settings
markdown: kramdown


collections:
  schapirozichronos:
    output: true
    title: "Rabbi Schapiro's Zichronos"
    description: Rabbi Yehuda Leib Schapiro tells his zichronos of the Lubavitcher Rebbe.
    url: /schapirozichronos/
    image: /schapirozichronos/image.jpg
    keywords: 
      - zichronos
      - chassidus
      - rebbe
      - chabad
      - lubavitch
defaults:
  - scope:
      path: ""
      type: schapirozichronos
    values:
      layout: podcast
      name: "track"
      file:
      - ext: .m4a
        length: -1
        mime: audio/x-m4a
        duration: "00:00"
      explicit: no
      block: no

