# Site settings
title: Chaim Leib Halbert
email: chaim.leib.halbert@gmail.com
description: > # this means to ignore newlines until "baseurl:"  
  <ul>Other blogs:
      <li><a href='https://manhacking.blogspot.com/'>man hacking</a></li>
      <li><a href='https://unlabeledjew.blogspot.com/'>Unlabeled Jew</a></li>
  </ul>
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://chaimleib.github.io" # the base hostname & protocol for your site
twitter_username: ChaimHalbert
github_username:  chaimleib

# Build settings
markdown: kramdown


collections:
  shapiro_zichronos:
    output: true
defaults:
  - scope:
      path: ""
      type: shapiro_zichronos
    values:
      layout: podcast

