# Site settings
title: Chaim Leib Halbert
ogTitle: Chaim Leib
author: Chaim Leib Halbert
email: chaim.leib.halbert@gmail.com
description: Chaim Leib is a software engineer in Arizona. He enjoys coding, tinkering, martial arts, music and being as Jewish as he can be.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://chaimleib.github.io" # the base hostname & protocol for your site
lang: en
twitter_username: ChaimHalbert
github_username: chaimleib

# Build settings
markdown: kramdown


collections:
  audio:
    output: true
    title: "Audio"
    description: Audio that Chaim created.
    url: /audio/
    keywords:
      - audio
      - recording
defaults:
  - scope:
      path: ""
    values:
      ogType: article
  - scope:
      path: ""
      type: audio
    values:
      layout: podcast
      name: "track"
      file:
      - ext: .m4a
        length: -1
        mime: audio/x-m4a
        duration: "00:00"
      explicit: no
      block: no
      description: Audio that Chaim created.

