# Site settings
title: Chaim Leib Halbert
ogTitle: Chaim Leib
author: Chaim Leib Halbert
email: chaim.leib.halbert@gmail.com
description: Chaim Leib is a software engineer in Arizona. He enjoys coding, tinkering, martial arts, music and being as Jewish as he can be.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://chaimleib.github.io" # the base hostname & protocol for your site
lang: en
twitter_username: ChaimHalbert
github_username: chaimleib

# Build settings
markdown: kramdown


collections:
  audio:
    output: true
    title: "Audio"
    description: Audio that Chaim created.
    url: /audio/
    keywords:
      - audio
      - recording
  schapirozichronos:
    output: true
    title: "Rabbi Schapiro's Zichronos"
    description: Rabbi Yehuda Leib Schapiro tells his zichronos of the Lubavitcher Rebbe.
    url: /schapirozichronos/
    image: /schapirozichronos/image.jpg
    keywords:
      - zichronos
      - chassidus
      - rebbe
      - chabad
      - lubavitch
      - schapiro
  seligsonzichronos:
    output: true
    title: "Rabbi Seligson's Zichronos"
    description: Rabbi Michoel Seligson tells his zichronos of the Lubavitcher Rebbe.
    url: /seligsonzichronos/
    keywords:
      - zichronos
      - chassidus
      - rebbe
      - chabad
      - lubavitch
      - seligson
defaults:
  - scope:
      path: ""
    values:
      ogType: article
  - scope:
      path: ""
      type: audio
    values:
      layout: podcast
      name: "track"
      file:
      - ext: .m4a
        length: -1
        mime: audio/x-m4a
        duration: "00:00"
      explicit: no
      block: no
      description: Audio that Chaim created.
  - scope:
      path: ""
      type: schapirozichronos
    values:
      layout: podcast
      name: "track"
      file:
      - ext: .m4a
        length: -1
        mime: audio/x-m4a
        duration: "00:00"
      explicit: no
      block: no
      description: Rabbi Yehuda Leib Schapiro's memories of the Lubavitcher Rebbe.
  - scope:
      path: ""
      type: seligsonzichronos
    values:
      layout: podcast
      name: "track"
      file:
      - ext: .m4a
        length: -1
        mime: audio/x-m4a
        duration: "00:00"
      explicit: no
      block: no
      description: Rabbi Michoel Seligson's memories of the Lubavitcher Rebbe.

